{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(11388, 9)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>DOI</th>\n",
       "      <th>Title</th>\n",
       "      <th>Container Title</th>\n",
       "      <th>Publisher</th>\n",
       "      <th>Publish Date</th>\n",
       "      <th>Author First Name</th>\n",
       "      <th>Author Last Name</th>\n",
       "      <th>Author Order</th>\n",
       "      <th>Referenced By</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>10.35366/99957</td>\n",
       "      <td>Qué debe llevar un resumen</td>\n",
       "      <td>Cirujano General</td>\n",
       "      <td>GRAPHIMEDIC SA DE CV</td>\n",
       "      <td>[2020]</td>\n",
       "      <td>Abilene Cirenia</td>\n",
       "      <td>Escamilla Ortiz</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>10.34117/bjdv6n3-358</td>\n",
       "      <td>Perfil socioeconômico de mulheres feirantes do...</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>[2020]</td>\n",
       "      <td>Jessé Rafael Bento</td>\n",
       "      <td>Lima</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>10.34117/bjdv6n3-358</td>\n",
       "      <td>Perfil socioeconômico de mulheres feirantes do...</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>[2020]</td>\n",
       "      <td>Clayton dos Santos</td>\n",
       "      <td>Silva</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>10.34117/bjdv6n3-358</td>\n",
       "      <td>Perfil socioeconômico de mulheres feirantes do...</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>[2020]</td>\n",
       "      <td>Romário Guimarães Verçosa</td>\n",
       "      <td>Araújo</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>10.34117/bjdv6n3-358</td>\n",
       "      <td>Perfil socioeconômico de mulheres feirantes do...</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>[2020]</td>\n",
       "      <td>Jonas Olimpio de Lima</td>\n",
       "      <td>Silva</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>10.34117/bjdv6n3-358</td>\n",
       "      <td>Perfil socioeconômico de mulheres feirantes do...</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>[2020]</td>\n",
       "      <td>Arlla Katherine Xavier</td>\n",
       "      <td>Lima</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>10.34117/bjdv6n3-358</td>\n",
       "      <td>Perfil socioeconômico de mulheres feirantes do...</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>[2020]</td>\n",
       "      <td>João Manoel</td>\n",
       "      <td>Silva</td>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>10.34117/bjdv6n3-358</td>\n",
       "      <td>Perfil socioeconômico de mulheres feirantes do...</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>[2020]</td>\n",
       "      <td>Tania Marta Carvalho</td>\n",
       "      <td>Santos</td>\n",
       "      <td>7</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>10.34117/bjdv6n3-358</td>\n",
       "      <td>Perfil socioeconômico de mulheres feirantes do...</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>Brazilian Journal of Development</td>\n",
       "      <td>[2020]</td>\n",
       "      <td>Jakes Halan de Queiroz</td>\n",
       "      <td>Costa</td>\n",
       "      <td>8</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>10.5194/egusphere-egu2020-1598</td>\n",
       "      <td>The storage and influencing factors of mercury...</td>\n",
       "      <td></td>\n",
       "      <td>Copernicus GmbH</td>\n",
       "      <td>[]</td>\n",
       "      <td>Jing</td>\n",
       "      <td>Gu</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>10.5194/egusphere-egu2020-1598</td>\n",
       "      <td>The storage and influencing factors of mercury...</td>\n",
       "      <td></td>\n",
       "      <td>Copernicus GmbH</td>\n",
       "      <td>[]</td>\n",
       "      <td>Qiaotong</td>\n",
       "      <td>Pang</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>10.5194/egusphere-egu2020-1598</td>\n",
       "      <td>The storage and influencing factors of mercury...</td>\n",
       "      <td></td>\n",
       "      <td>Copernicus GmbH</td>\n",
       "      <td>[]</td>\n",
       "      <td>Jinzhi</td>\n",
       "      <td>Ding</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>10.5194/egusphere-egu2020-1598</td>\n",
       "      <td>The storage and influencing factors of mercury...</td>\n",
       "      <td></td>\n",
       "      <td>Copernicus GmbH</td>\n",
       "      <td>[]</td>\n",
       "      <td>Runsheng</td>\n",
       "      <td>Yin</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>10.5194/egusphere-egu2020-1598</td>\n",
       "      <td>The storage and influencing factors of mercury...</td>\n",
       "      <td></td>\n",
       "      <td>Copernicus GmbH</td>\n",
       "      <td>[]</td>\n",
       "      <td>Yuanhe</td>\n",
       "      <td>Yang</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>10.5194/egusphere-egu2020-1598</td>\n",
       "      <td>The storage and influencing factors of mercury...</td>\n",
       "      <td></td>\n",
       "      <td>Copernicus GmbH</td>\n",
       "      <td>[]</td>\n",
       "      <td>Yanxu</td>\n",
       "      <td>Zhang</td>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>10.47240/revistadaesg.v34i72.1118</td>\n",
       "      <td>ANÁLISE CONSTRUTIVISTA DA DEMOCRATIZAÇÃO EM TA...</td>\n",
       "      <td>Revista da Escola Superior de Guerra</td>\n",
       "      <td>Revista da Escola Superior de Guerra</td>\n",
       "      <td>[]</td>\n",
       "      <td>Douglas Rocha</td>\n",
       "      <td>Almeida</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>10.47240/revistadaesg.v34i72.1118</td>\n",
       "      <td>ANÁLISE CONSTRUTIVISTA DA DEMOCRATIZAÇÃO EM TA...</td>\n",
       "      <td>Revista da Escola Superior de Guerra</td>\n",
       "      <td>Revista da Escola Superior de Guerra</td>\n",
       "      <td>[]</td>\n",
       "      <td>Fábio Albergaria</td>\n",
       "      <td>De Queiroz</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>10.37972/chgpu.2020.99.85.024</td>\n",
       "      <td>ПРИМЕНЕНИЕ РЕКРЕАЦИОННО-ОЗДОРОВИТЕЛЬНЫХ ПРАКТИ...</td>\n",
       "      <td>Bulletin of the Chuvash State Pedagogical Univ...</td>\n",
       "      <td>Yakovlev Chuvash State Pedagogical University</td>\n",
       "      <td>[]</td>\n",
       "      <td>Gulnur</td>\n",
       "      <td>Kamalova</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>10.1101/2020.10.20.344226</td>\n",
       "      <td>The data-index: an author-level metric that va...</td>\n",
       "      <td></td>\n",
       "      <td>Cold Spring Harbor Laboratory</td>\n",
       "      <td>[]</td>\n",
       "      <td>Amelia S C</td>\n",
       "      <td>Hood</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>10.1101/2020.10.20.344226</td>\n",
       "      <td>The data-index: an author-level metric that va...</td>\n",
       "      <td></td>\n",
       "      <td>Cold Spring Harbor Laboratory</td>\n",
       "      <td>[]</td>\n",
       "      <td>William J</td>\n",
       "      <td>Sutherland</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                  DOI  \\\n",
       "0                      10.35366/99957   \n",
       "1                10.34117/bjdv6n3-358   \n",
       "2                10.34117/bjdv6n3-358   \n",
       "3                10.34117/bjdv6n3-358   \n",
       "4                10.34117/bjdv6n3-358   \n",
       "5                10.34117/bjdv6n3-358   \n",
       "6                10.34117/bjdv6n3-358   \n",
       "7                10.34117/bjdv6n3-358   \n",
       "8                10.34117/bjdv6n3-358   \n",
       "9      10.5194/egusphere-egu2020-1598   \n",
       "10     10.5194/egusphere-egu2020-1598   \n",
       "11     10.5194/egusphere-egu2020-1598   \n",
       "12     10.5194/egusphere-egu2020-1598   \n",
       "13     10.5194/egusphere-egu2020-1598   \n",
       "14     10.5194/egusphere-egu2020-1598   \n",
       "15  10.47240/revistadaesg.v34i72.1118   \n",
       "16  10.47240/revistadaesg.v34i72.1118   \n",
       "17      10.37972/chgpu.2020.99.85.024   \n",
       "18          10.1101/2020.10.20.344226   \n",
       "19          10.1101/2020.10.20.344226   \n",
       "\n",
       "                                                Title  \\\n",
       "0                          Qué debe llevar un resumen   \n",
       "1   Perfil socioeconômico de mulheres feirantes do...   \n",
       "2   Perfil socioeconômico de mulheres feirantes do...   \n",
       "3   Perfil socioeconômico de mulheres feirantes do...   \n",
       "4   Perfil socioeconômico de mulheres feirantes do...   \n",
       "5   Perfil socioeconômico de mulheres feirantes do...   \n",
       "6   Perfil socioeconômico de mulheres feirantes do...   \n",
       "7   Perfil socioeconômico de mulheres feirantes do...   \n",
       "8   Perfil socioeconômico de mulheres feirantes do...   \n",
       "9   The storage and influencing factors of mercury...   \n",
       "10  The storage and influencing factors of mercury...   \n",
       "11  The storage and influencing factors of mercury...   \n",
       "12  The storage and influencing factors of mercury...   \n",
       "13  The storage and influencing factors of mercury...   \n",
       "14  The storage and influencing factors of mercury...   \n",
       "15  ANÁLISE CONSTRUTIVISTA DA DEMOCRATIZAÇÃO EM TA...   \n",
       "16  ANÁLISE CONSTRUTIVISTA DA DEMOCRATIZAÇÃO EM TA...   \n",
       "17  ПРИМЕНЕНИЕ РЕКРЕАЦИОННО-ОЗДОРОВИТЕЛЬНЫХ ПРАКТИ...   \n",
       "18  The data-index: an author-level metric that va...   \n",
       "19  The data-index: an author-level metric that va...   \n",
       "\n",
       "                                      Container Title  \\\n",
       "0                                    Cirujano General   \n",
       "1                    Brazilian Journal of Development   \n",
       "2                    Brazilian Journal of Development   \n",
       "3                    Brazilian Journal of Development   \n",
       "4                    Brazilian Journal of Development   \n",
       "5                    Brazilian Journal of Development   \n",
       "6                    Brazilian Journal of Development   \n",
       "7                    Brazilian Journal of Development   \n",
       "8                    Brazilian Journal of Development   \n",
       "9                                                       \n",
       "10                                                      \n",
       "11                                                      \n",
       "12                                                      \n",
       "13                                                      \n",
       "14                                                      \n",
       "15               Revista da Escola Superior de Guerra   \n",
       "16               Revista da Escola Superior de Guerra   \n",
       "17  Bulletin of the Chuvash State Pedagogical Univ...   \n",
       "18                                                      \n",
       "19                                                      \n",
       "\n",
       "                                        Publisher Publish Date  \\\n",
       "0                            GRAPHIMEDIC SA DE CV       [2020]   \n",
       "1                Brazilian Journal of Development       [2020]   \n",
       "2                Brazilian Journal of Development       [2020]   \n",
       "3                Brazilian Journal of Development       [2020]   \n",
       "4                Brazilian Journal of Development       [2020]   \n",
       "5                Brazilian Journal of Development       [2020]   \n",
       "6                Brazilian Journal of Development       [2020]   \n",
       "7                Brazilian Journal of Development       [2020]   \n",
       "8                Brazilian Journal of Development       [2020]   \n",
       "9                                 Copernicus GmbH           []   \n",
       "10                                Copernicus GmbH           []   \n",
       "11                                Copernicus GmbH           []   \n",
       "12                                Copernicus GmbH           []   \n",
       "13                                Copernicus GmbH           []   \n",
       "14                                Copernicus GmbH           []   \n",
       "15           Revista da Escola Superior de Guerra           []   \n",
       "16           Revista da Escola Superior de Guerra           []   \n",
       "17  Yakovlev Chuvash State Pedagogical University           []   \n",
       "18                  Cold Spring Harbor Laboratory           []   \n",
       "19                  Cold Spring Harbor Laboratory           []   \n",
       "\n",
       "            Author First Name Author Last Name  Author Order  Referenced By  \n",
       "0             Abilene Cirenia  Escamilla Ortiz             1              0  \n",
       "1          Jessé Rafael Bento             Lima             1              0  \n",
       "2          Clayton dos Santos            Silva             2              0  \n",
       "3   Romário Guimarães Verçosa           Araújo             3              0  \n",
       "4       Jonas Olimpio de Lima            Silva             4              0  \n",
       "5      Arlla Katherine Xavier             Lima             5              0  \n",
       "6                 João Manoel            Silva             6              0  \n",
       "7        Tania Marta Carvalho           Santos             7              0  \n",
       "8      Jakes Halan de Queiroz            Costa             8              0  \n",
       "9                        Jing               Gu             1              0  \n",
       "10                   Qiaotong             Pang             2              0  \n",
       "11                     Jinzhi             Ding             3              0  \n",
       "12                   Runsheng              Yin             4              0  \n",
       "13                     Yuanhe             Yang             5              0  \n",
       "14                      Yanxu            Zhang             6              0  \n",
       "15              Douglas Rocha          Almeida             1              0  \n",
       "16           Fábio Albergaria       De Queiroz             2              0  \n",
       "17                     Gulnur         Kamalova             1              0  \n",
       "18                 Amelia S C             Hood             1              0  \n",
       "19                  William J       Sutherland             2              0  "
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "import pandas as pd\n",
    "\n",
    "rows = 1000\n",
    "\n",
    "def get_articles_by_year(year, rows=rows):\n",
    "    base_url = 'https://api.crossref.org/works'\n",
    "    params = {\n",
    "        'filter': f'from-pub-date:{year}-01-01,until-pub-date:{year}-12-31',\n",
    "        'sort': 'relevance',\n",
    "        'rows': rows  # Adjust this number to change the number of articles per year\n",
    "    }\n",
    "\n",
    "    articles = []\n",
    "    cursor = '*'\n",
    "\n",
    "    while cursor:\n",
    "        response = requests.get(base_url, params=params)\n",
    "        if response.status_code == 200:\n",
    "            data = response.json()\n",
    "            items = data.get('message', {}).get('items', [])\n",
    "            \n",
    "            if not items:\n",
    "                break\n",
    "            \n",
    "            articles.extend(items)\n",
    "            cursor = data.get('message', {}).get('next-cursor', '')\n",
    "        else:\n",
    "            print(f\"Request failed with status code: {response.status_code}\")\n",
    "            print(response.content)\n",
    "            break\n",
    "\n",
    "    return articles\n",
    "\n",
    "years_to_pull = [2020, 2021, 2022, 2023]\n",
    "all_articles = []\n",
    "\n",
    "for year in years_to_pull:\n",
    "    articles = get_articles_by_year(year, rows = rows)  # Adjust this number for the desired articles per year\n",
    "    all_articles.extend(articles)\n",
    "\n",
    "data = {\n",
    "    'DOI': [],\n",
    "    'Title': [],\n",
    "    'Container Title': [],\n",
    "    'Publisher': [],\n",
    "    'Publish Date': [],\n",
    "    'Author First Name': [],\n",
    "    'Author Last Name': [],\n",
    "    'Author Order': [],\n",
    "    'Referenced By': []\n",
    "}\n",
    "\n",
    "for article in all_articles:\n",
    "    doi = article.get('DOI', '')\n",
    "    title = article.get('title', [''])[0]\n",
    "    container_title = article.get('container-title', [''])[0]\n",
    "    publisher = article.get('publisher', '')\n",
    "    publish_date = article.get('published-print', {}).get('date-parts', [[]])[0]\n",
    "    authors = article.get('author', [])\n",
    "    referenced_by = article.get('is-referenced-by-count', 0)\n",
    "\n",
    "    for order, author in enumerate(authors, start=1):\n",
    "        first_name = author.get('given', '')\n",
    "        last_name = author.get('family', '')\n",
    "        \n",
    "        data['DOI'].append(doi)\n",
    "        data['Title'].append(title)\n",
    "        data['Container Title'].append(container_title)\n",
    "        data['Publisher'].append(publisher)\n",
    "        data['Publish Date'].append(publish_date)\n",
    "        data['Author First Name'].append(first_name)\n",
    "        data['Author Last Name'].append(last_name)\n",
    "        data['Author Order'].append(order)\n",
    "        data['Referenced By'].append(referenced_by)\n",
    "\n",
    "df = pd.DataFrame(data)\n",
    "df.columns = ['DOI', 'Title', 'Container Title', 'Publisher', 'Publish Date', 'Author First Name', 'Author Last Name', 'Author Order', 'Referenced By']\n",
    "print(df.shape)\n",
    "df.head(20)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
